name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
    chatId:
        description: 'Telegram Chat Id'
        required: true
    event:
        description: GitHub event
        required: true
outputs:
    time:
        description: 'The time we greeted you'
runs:
    using: 'node12'
    main: 'index.js'